### ISSUE TITLE
hc-table cells aren't centered vertically

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#233]
In tables.scss:

```scss
table.hc-table {
  ...
  tbody {
    ...
    td {
      vertical-align: top;
    }
  }
}
```

Why are cells top-aligned? It makes them look off-balance:

![image](https://user-images.githubusercontent.com/9139369/39072413-abe828a4-44a7-11e8-8fb7-bb96497ca953.png)

Can we make this `vertical-align: middle`?
