### ISSUE TITLE
`hc-input` in IE is too short

### ISSUE THREAD

**Issue by joeskeen** [HealthCatalyst/Fabric.Cashmere#240]
The Cashmere inputs in IE don't display tall enough; placeholder and entered text gets cut off:

![image](https://user-images.githubusercontent.com/12286274/39723815-2db3d75c-5204-11e8-85a0-a70d0ba3c9db.png)

This is what I did to fix this in Atlas as a quick hack to get the release out.  I imagine a more responsible fix is possible.

```scss
input.hc-input, div.input-icon {
    height: 35px !important;
}
```
