### ISSUE TITLE
`hc-pagination` buttons are huge in IE

### ISSUE THREAD

**Issue by joeskeen** [HealthCatalyst/Fabric.Cashmere#241]
The pagination control buttons all display very large, even those that have little content:
![image](https://user-images.githubusercontent.com/12286274/39724006-be42efba-5204-11e8-9677-7f8e877d2b7a.png)

This is the fix I made in Atlas as a hack to get the release out.  I expect a more responsible fix is possible.

```scss
.hc-inner-button, .hc-left-button, .hc-right-button {
    min-width: 15px !important;
}
```
